version: '3.8'

services:
  drupal:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: drupal_app
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./config:/var/www/html/config
      - ./composer.json:/var/www/html/composer.json
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    depends_on:
      - db
    networks:
      - drupal_network

  db:
    image: mysql:8.0
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drupal_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: drupal
      PMA_PASSWORD: drupal
    depends_on:
      - db
    networks:
      - drupal_network

volumes:
  db_data:

networks:
  drupal_network:
    driver: bridge
